rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-2.0
  - jruby

before_script: "sudo ntpdate -ub ntp.ubuntu.com pool.ntp.org; true"
script: "bundle exec rake spec cucumber"

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
